---
# Copyright 2017, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Check if we already ran this
- name: Check for /var/tmp/octavia_secret.run
  stat:
    path: /var/tmp/octavia_secret.run
  register: stat_result

# Append to secrets file
- name: Add Octavia secrets to /etc/openstacl_deploy
  blockinfile:
    dest: '/etc/openstack_deploy/user_secrets.yml'
    block: |
      octavia_container_mysql_password:
      octavia_service_password:
      octavia_health_hmac_key:
      octavia_rabbitmq_password:
  when: stat_result.stat.exists == False

# Run only once
- name: Generate new secrets
  shell: "/opt/ansible-runtime/bin/python /opt/rpc-openstack/openstack-ansible/scripts/pw-token-gen.py --file /etc/openstack_deploy/user_secrets.yml && touch /var/tmp/octavia_secret.run"
  args:
    creates: /var/tmp/octavia_secret.run
